package reader;

import edu.uj.elms.entities.BookCopyEntity;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Collection;
import javax.swing.table.DefaultTableModel;
import edu.uj.elms.beans.BookCopy;
import java.util.ResourceBundle;

/**
 * @author  Karolina
 */
public class BorrowedPanel extends javax.swing.JPanel {
    
    private SessionData sData;
    private StatePanel parentPanel;
    
    /** Creates new form BorrowedPanel */
    public BorrowedPanel(SessionData s) {
        initComponents();
        this.setVisible(false);
        sData = s;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        codePanel = new javax.swing.JPanel();
        tmpLabel = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        borrowedTable = new javax.swing.JTable();
        titlePanel = new javax.swing.JPanel();
        titileLabel = new javax.swing.JLabel();
        borrowedLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();

        codePanel.setBackground(new java.awt.Color(0, 204, 204));
        tmpLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        tmpLabel.setText(java.util.ResourceBundle.getBundle("reader/reader").getString("cart_number"));

        numberLabel.setFont(new java.awt.Font("Tahoma", 2, 12));

        org.jdesktop.layout.GroupLayout codePanelLayout = new org.jdesktop.layout.GroupLayout(codePanel);
        codePanel.setLayout(codePanelLayout);
        codePanelLayout.setHorizontalGroup(
            codePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, codePanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .add(tmpLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(numberLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 249, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21))
        );
        codePanelLayout.setVerticalGroup(
            codePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(codePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(codePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tmpLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(numberLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        borrowedTable.setFont(new java.awt.Font("Arial", 0, 12));
        borrowedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ResourceBundle.getBundle("reader/reader").getString("author"), 
				ResourceBundle.getBundle("reader/reader").getString("title"), 
				ResourceBundle.getBundle("reader/reader").getString("publisher"),
				ResourceBundle.getBundle("reader/reader").getString("book_id"), 
				ResourceBundle.getBundle("reader/reader").getString("return_date")
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        borrowedTable.setSelectionBackground(new java.awt.Color(0, 204, 204));
        jScrollPane1.setViewportView(borrowedTable);

        org.jdesktop.layout.GroupLayout tablePanelLayout = new org.jdesktop.layout.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, tablePanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        titileLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        titileLabel.setText(java.util.ResourceBundle.getBundle("reader/reader").getString("borrowed_books"));

        borrowedLabel.setFont(new java.awt.Font("Tahoma", 1, 12));

        org.jdesktop.layout.GroupLayout titlePanelLayout = new org.jdesktop.layout.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(titlePanelLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(titileLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(borrowedLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(titlePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(titileLabel)
                    .add(borrowedLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        returnButton.setFont(new java.awt.Font("Tahoma", 1, 12));
        returnButton.setText(java.util.ResourceBundle.getBundle("reader/reader").getString("back"));
        returnButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                returnButtonKeyPressed(evt);
            }
        });
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(codePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 75, Short.MAX_VALUE)
                .add(returnButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(35, 35, 35))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(titlePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tablePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(codePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(returnButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(titlePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tablePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_returnButtonKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            this.returnButtonAccept();
        }
    }//GEN-LAST:event_returnButtonKeyPressed

    private void returnButtonAccept(){
        this.setVisible(false);
        this.clearFields();
        parentPanel.setVisible(true);    
    }
    
    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        this.returnButtonAccept();
    }//GEN-LAST:event_returnButtonMouseClicked

    public void displayResults(Collection<BookCopy> books){
        this.numberLabel.setText(sData.getLogin());
        this.borrowedLabel.setText(Integer.toString(books.size()));
        this.tablePanel.setVisible(books.size()>0);
        for (BookCopy b : books) {
            Object[] obj = new Object[5];
            obj[0] = b.getBook().getAuthor();
            obj[1] = b.getBook().getTitle();
            obj[2] = b.getBook().getPublisher() + ", " + Integer.toString(b.getBook().getPublishYear());
            obj[3] = b.getCopyId();
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd"); 
            obj[4] = df.format(b.getReturnDate().getTime());
   
            ((DefaultTableModel)this.borrowedTable.getModel()).addRow(obj);
        }
    }
    
    private void clearFields(){
        this.numberLabel.setText("");
        this.borrowedLabel.setText("");
        this.tablePanel.setVisible(true);
         
        int j = this.borrowedTable.getRowCount();
        for(int i = 0 ; i < j ; i++){
            ((DefaultTableModel)this.borrowedTable.getModel()).removeRow(0);
        }
    }
    
    public void setParentPanel(StatePanel s) { parentPanel = s; }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borrowedLabel;
    private javax.swing.JTable borrowedTable;
    private javax.swing.JPanel codePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel titileLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel tmpLabel;
    // End of variables declaration//GEN-END:variables
    
}
