package reader;

import edu.uj.elms.session.ReaderSessionRemote;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import edu.uj.elms.beans.LoginData;
import edu.uj.elms.exceptions.LibraryException;
import javax.naming.InitialContext;

/**
 * @author  Karolina
 */
public class LoginPanel extends javax.swing.JPanel {
    
    private MenuPanel menuPanel;
    private SessionData sData;
    
    /** Creates new form LoginPanel */
    public LoginPanel(SessionData sd) {
        initComponents();
        sData = sd;
        clearFields();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        internalPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        acceptButton = new javax.swing.JButton();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        internalPanel.setBackground(new java.awt.Color(0, 204, 204));
        loginLabel.setFont(new java.awt.Font("Arial", 1, 14));
        loginLabel.setText(java.util.ResourceBundle.getBundle("reader/reader").getString("login_"));

        passLabel.setFont(new java.awt.Font("Arial", 1, 14));
        passLabel.setText(java.util.ResourceBundle.getBundle("reader/reader").getString("password_"));

        loginTextField.setFont(new java.awt.Font("Tahoma", 0, 12));

        acceptButton.setFont(new java.awt.Font("Tahoma", 1, 12));
        acceptButton.setText(java.util.ResourceBundle.getBundle("reader/reader").getString("log_in"));
        acceptButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                acceptButtonKeyPressed(evt);
            }
        });
        acceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptButtonMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout internalPanelLayout = new org.jdesktop.layout.GroupLayout(internalPanel);
        internalPanel.setLayout(internalPanelLayout);
        internalPanelLayout.setHorizontalGroup(
            internalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(internalPanelLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(internalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(loginLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(passLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(internalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(passField)
                    .add(loginTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, internalPanelLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .add(acceptButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(102, 102, 102))
        );
        internalPanelLayout.setVerticalGroup(
            internalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(internalPanelLayout.createSequentialGroup()
                .add(32, 32, 32)
                .add(internalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(loginLabel)
                    .add(loginTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(internalPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(passLabel)
                    .add(passField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                .add(acceptButton)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .add(internalPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(176, 176, 176)
                .add(internalPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER){
            this.accept();
        }
    }//GEN-LAST:event_formKeyPressed
    
    private void acceptButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acceptButtonKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER){
            this.accept();
        }
    }//GEN-LAST:event_acceptButtonKeyPressed
    
    private void acceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptButtonMouseClicked
        this.accept();
    }//GEN-LAST:event_acceptButtonMouseClicked
    
    private void accept(){
        if (checkLogin()){
            this.setVisible(false);
            this.clearFields();
            menuPanel.activatePanel();
        }
    }
    private boolean checkLogin(){
        String login = this.loginTextField.getText();
        int loginInt =0;
        try{
            loginInt = Integer.parseInt(login);
            LoginData ldata = new LoginData(); // anonymous
            
            sData.setLogin(login);
            InitialContext ctx = new InitialContext();
            ReaderSessionRemote library = (ReaderSessionRemote) ctx.lookup("ReaderSession");
            
            if (loginInt != 0){
                ldata = new LoginData(loginInt, new String(this.passField.getPassword()));
                library.logIn(ldata);
            }
            
            sData.setLibrary(library);
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, 
                    ResourceBundle.getBundle("reader/reader").getString("wrong_login_or_password"),
                    ResourceBundle.getBundle("reader/reader").getString("warning"),
                    JOptionPane.WARNING_MESSAGE);
            return(false);
        }catch(Exception e){
            if (e instanceof LibraryException) {
                JOptionPane.showMessageDialog(this, e.getLocalizedMessage(), 
                        ResourceBundle.getBundle("reader/reader").getString("warning"),
                        JOptionPane.WARNING_MESSAGE);
            } else {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, 
                        ResourceBundle.getBundle("reader/reader").getString("problems_with_connection"),
                        ResourceBundle.getBundle("reader/reader").getString("warning"),
                        JOptionPane.WARNING_MESSAGE);
            }
            return(false);
        }
        return(true);
    }
    
    public void setChildPanel(MenuPanel m){menuPanel = m;}
    
    private void clearFields(){
        this.loginTextField.setText("0");
        this.passField.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JPanel internalPanel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    // End of variables declaration//GEN-END:variables
    
}
